services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - type: bind
        source: ../
        target: /workspaces/fumimi-channel
        consistency: cached
    init: true