/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardBoardKeyRouteImport } from './routes/board.$boardKey'
import { Route as BoardBoardKeyThreadThreadIdRouteImport } from './routes/board.$boardKey.thread.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardKeyRoute = BoardBoardKeyRouteImport.update({
  id: '/board/$boardKey',
  path: '/board/$boardKey',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardKeyThreadThreadIdRoute =
  BoardBoardKeyThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => BoardBoardKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board/$boardKey': typeof BoardBoardKeyRouteWithChildren
  '/board/$boardKey/thread/$threadId': typeof BoardBoardKeyThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/$boardKey': typeof BoardBoardKeyRouteWithChildren
  '/board/$boardKey/thread/$threadId': typeof BoardBoardKeyThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board/$boardKey': typeof BoardBoardKeyRouteWithChildren
  '/board/$boardKey/thread/$threadId': typeof BoardBoardKeyThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board/$boardKey' | '/board/$boardKey/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board/$boardKey' | '/board/$boardKey/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/board/$boardKey'
    | '/board/$boardKey/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardBoardKeyRoute: typeof BoardBoardKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardKey': {
      id: '/board/$boardKey'
      path: '/board/$boardKey'
      fullPath: '/board/$boardKey'
      preLoaderRoute: typeof BoardBoardKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardKey/thread/$threadId': {
      id: '/board/$boardKey/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/board/$boardKey/thread/$threadId'
      preLoaderRoute: typeof BoardBoardKeyThreadThreadIdRouteImport
      parentRoute: typeof BoardBoardKeyRoute
    }
  }
}

interface BoardBoardKeyRouteChildren {
  BoardBoardKeyThreadThreadIdRoute: typeof BoardBoardKeyThreadThreadIdRoute
}

const BoardBoardKeyRouteChildren: BoardBoardKeyRouteChildren = {
  BoardBoardKeyThreadThreadIdRoute: BoardBoardKeyThreadThreadIdRoute,
}

const BoardBoardKeyRouteWithChildren = BoardBoardKeyRoute._addFileChildren(
  BoardBoardKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardBoardKeyRoute: BoardBoardKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
